###
POST http://localhost:3000/api/services
Content-Type: application/json

{
    "name": "Centro são jose",
    "adress": "Rua Luis de nogueira, 235",
    "location": "João Pessoa",
    "currentPeople": 49,
    "maxPeople": 50,
    "doctors": 3,
    "volunteers": 4,
    "vehicles": 3,
    "kits": 100,
    "basicBasket": 50
}

###
GET http://localhost:3000/api/services

###
GET http://localhost:3000/api/services/66ac35364ca202e98576acf0

###
PUT http://localhost:3000/api/services/66ac35364ca202e98576acf0
Content-Type: application/json

{
    "currentPeople": 10,
    "doctors": 5,
    "volunteers": 1,
    "vehicles": 4,
    "kits": 150,
    "basicBasket": 300
}